import json

cells = []

# Cell 0: Markdown
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Gemma 4 26B A4B Vision — FLN Worksheet Question Splitter (Colab)\n\n"
        "Extracts **every individual question** from a worksheet image using intelligent segmentation,  \n"
        "then analyzes each crop separately with Gemma 4 26B A4B. Outputs a **per-question JSON**  \n"
        "with complete visible content — text, objects, answer spaces, structure — WITHOUT answers.\n\n"
        "---\n"
        "**Setup**  \n"
        "1. Runtime \u2192 Change runtime type \u2192 **T4 GPU** (high-RAM) or **A100**  \n"
        "2. Add HF_TOKEN to Colab Secrets (\U0001f511 key icon) \u2192 Add **HF_TOKEN**  \n"
        "3. Run all cells below\n\n"
        "---\n"
        "**How it works:**  \n"
        "1. Preprocess image (deskew, sharpen, CLAHE)  \n"
        "2. Segment into individual question regions via projection profiles  \n"
        "3. Filter headders/footers/noise, recursively split large regions  \n"
        "4. Send EACH crop to Gemma with a comprehensive extract-everything prompt  \n"
        "5. Collect per-question JSON into worksheet-level output\n\n"
        "---\n"
        "**Important Notes:**  \n"
        "- First run downloads the GGUF model (~17 GB, ~15-20 min on T4)  \n"
        "- Cached in `/root/gguf_cache/` after first download\n"
    ]
})

# Cell 1: Environment setup
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 0: Environment setup\n"
        "import os, shutil, time, json, re, base64, zipfile\n"
        "from pathlib import Path\n"
        "from IPython.display import display, Image as IPyImage\n\n"
        "OUTPUT_DIR = \"/content/FLN_Results\"\n"
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n"
        "print(f\"Outputs: {OUTPUT_DIR}\")\n\n"
        "total, used, free = shutil.disk_usage(\"/content/\")\n"
        "print(f\"Disk free: {free // (1024**3)} GB\")\n\n"
        "import subprocess\n"
        "subprocess.run([\"pip\", \"cache\", \"purge\"], capture_output=True)\n"
        "print(\"Ready\")\n"
    ]
})

# Cell 2: GPU check + deps
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 1: GPU check + Install deps\n"
        "import torch\n"
        "if not torch.cuda.is_available():\n"
        "    raise SystemExit('NO GPU. Go to Runtime > Change runtime type > GPU, then run again.')\n"
        "print(f\"GPU count: {torch.cuda.device_count()}\")\n"
        "for i in range(torch.cuda.device_count()):\n"
        "    print(f\"  GPU {i}: {torch.cuda.get_device_name(i)}\")\n"
        "print(f\"  VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.1f} GB\")\n\n"
        "total_vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)\n"
        "if total_vram_gb < 18:\n"
        "    print(f\"\\n\u26a0\ufe0f  WARNING: Only {total_vram_gb:.0f} GB VRAM available.\")\n"
        "    print(\"   Gemma 4 26B A4B (Q5_K_XL) needs ~17 GB.\")\n"
        "    print(\"   If you hit OOM errors, edit Cell 3 to use Q4_K_M instead.\\n\")\n\n"
        "!pip install opencv-python -q 2>&1 | tail -1\n"
        "!pip install pymupdf -q 2>&1 | tail -1\n"
        "import cv2, numpy as np\n"
        "print(\"Ready\")\n"
    ]
})

# Cell 3: Hugging Face Login
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 2: Hugging Face Login\n"
        "from huggingface_hub import login\n\n"
        "token = None\n"
        "try:\n"
        "    from google.colab import userdata\n"
        "    token = userdata.get('HF_TOKEN')\n"
        "except Exception:\n"
        "    pass\n\n"
        "if not token:\n"
        "    token = os.environ.get('HF_TOKEN')\n\n"
        "if not token:\n"
        "    from getpass import getpass\n"
        "    print(\"HF_TOKEN not found in Colab Secrets or env vars.\")\n"
        "    token = getpass(\"Enter your Hugging Face token: \")\n\n"
        "if not token:\n"
        "    raise ValueError('HF_TOKEN is required. Get it from https://huggingface.co/settings/tokens')\n\n"
        "login(token)\n"
        "print(\"Logged in to Hugging Face\")\n"
    ]
})

# Cell 4: Load Gemma 4 26B
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 3: Load Gemma 4 26B A4B (MoE)\n"
        "import subprocess, sys\n\n"
        "torch_ver = torch.version.cuda or ''\n"
        "print(f\"Torch CUDA: {torch_ver}\")\n\n"
        "wheel_map = {\"12.1\": \"cu121\", \"12.2\": \"cu122\", \"12.3\": \"cu123\",\n"
        "             \"12.4\": \"cu124\", \"12.5\": \"cu125\", \"12.6\": \"cu126\"}\n"
        "cuda_wheel = wheel_map.get(torch_ver, 'cu124')\n"
        "print(f\"Using {cuda_wheel} wheel\")\n\n"
        "print(\"Installing llama-cpp-python...\")\n"
        "sys.stdout.flush()\n"
        "subprocess.check_call([\n"
        "    sys.executable, '-m', 'pip', 'install',\n"
        "    'llama-cpp-python',\n"
        "    f'--extra-index-url', f'https://abetlen.github.io/llama-cpp-python/whl/{cuda_wheel}',\n"
        "    '--force-reinstall', '--no-cache-dir', '-q'\n"
        "])\n"
        "print(\"llama-cpp-python installed\")\n\n"
        "from llama_cpp import Llama\n"
        "from llama_cpp.llama_chat_format import Gemma4ChatHandler\n\n"
        "CACHE_DIR = \"/root/gguf_cache\"\n"
        "os.makedirs(CACHE_DIR, exist_ok=True)\n\n"
        "CHAT_HANDLER = Gemma4ChatHandler.from_pretrained(\n"
        "    repo_id=\"unsloth/gemma-4-26B-A4B-it-GGUF\",\n"
        "    filename=\"mmproj-F16.gguf\",\n"
        "    local_dir=CACHE_DIR, verbose=False,\n"
        ")\n"
        "print(\"Chat handler OK\")\n\n"
        "total_vram = torch.cuda.get_device_properties(0).total_memory\n"
        "if total_vram >= 20 * (1024**3):\n"
        "    model_file = \"gemma-4-26B-A4B-it-UD-Q5_K_XL.gguf\"\n"
        "    print(\"Using Q5_K_XL (high quality)\")\n"
        "else:\n"
        "    model_file = \"gemma-4-26B-A4B-it-Q4_K_M.gguf\"\n"
        "    print(\"Using Q4_K_M (smaller, for limited VRAM)\")\n\n"
        "start = time.time()\n"
        "llm = Llama.from_pretrained(\n"
        "    repo_id=\"unsloth/gemma-4-26B-A4B-it-GGUF\",\n"
        "    filename=model_file,\n"
        "    local_dir=CACHE_DIR,\n"
        "    chat_handler=CHAT_HANDLER,\n"
        "    n_gpu_layers=-1, n_ctx=8192,\n"
        "    flash_attn=True, verbose=False,\n"
        ")\n"
        "t = (time.time()-start)/60\n"
        "print(f\"Model loaded in {t:.1f} min\")\n"
    ]
})

# Cell 5: Image preprocessing
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 4: Image preprocessing\n\n"
        "def preprocess(img):\n"
        "    h, w = img.shape[:2]\n"
        "    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)\n"
        "    lap_var = cv2.Laplacian(gray, cv2.CV_64F).var()\n"
        "    result = img.copy()\n"
        "    applied = []\n\n"
        "    is_blurry = lap_var < 80\n"
        "    is_small = min(h, w) < 800\n"
        "    is_low_contrast = (float(gray.max()) - float(gray.min())) < 100\n\n"
        "    edges = cv2.Canny(gray, 50, 150, apertureSize=3)\n"
        "    lines = cv2.HoughLines(edges, 1, np.pi/180, 200)\n"
        "    angle = 0.0\n"
        "    if lines is not None:\n"
        "        angles = []\n"
        "        for line in lines:\n"
        "            theta = line[0][1]\n"
        "            deg = np.degrees(theta) - 90\n"
        "            if abs(deg) < 30:\n"
        "                angles.append(deg)\n"
        "        if angles:\n"
        "            angle = np.median(angles)\n"
        "    is_skewed = abs(angle) > 3.0\n\n"
        "    if is_skewed:\n"
        "        M = cv2.getRotationMatrix2D((w/2, h/2), angle, 1.0)\n"
        "        result = cv2.warpAffine(result, M, (w, h),\n"
        "                               flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)\n"
        "        applied.append(f\"deskew {angle:.1f} deg\")\n"
        "        h, w = result.shape[:2]\n\n"
        "    if is_blurry:\n"
        "        blurred = cv2.GaussianBlur(result, (0, 0), 3.0)\n"
        "        sharp = cv2.addWeighted(result, 1.5, blurred, -0.5, 0)\n"
        "        sharp = np.clip(sharp, 0, 255).astype(np.uint8)\n"
        "        new_var = cv2.Laplacian(cv2.cvtColor(sharp, cv2.COLOR_RGB2GRAY), cv2.CV_64F).var()\n"
        "        if new_var > lap_var:\n"
        "            result = sharp\n"
        "            applied.append(\"unsharp\")\n\n"
        "    if is_low_contrast or is_blurry:\n"
        "        lab = cv2.cvtColor(result, cv2.COLOR_RGB2LAB)\n"
        "        l, a, b = cv2.split(lab)\n"
        "        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))\n"
        "        l = clahe.apply(l)\n"
        "        result = cv2.cvtColor(cv2.merge([l, a, b]), cv2.COLOR_LAB2RGB)\n"
        "        applied.append(\"CLAHE\")\n\n"
        "    if is_small:\n"
        "        scale = max(1.0, 800 / min(h, w))\n"
        "        if scale > 1.1:\n"
        "            result = cv2.resize(result, None, fx=scale, fy=scale,\n"
        "                               interpolation=cv2.INTER_CUBIC)\n"
        "            applied.append(f\"upscale {scale:.1f}x\")\n\n"
"    info = {\"blurry\": bool(is_blurry), \"skewed\": bool(is_skewed), \"small\": bool(is_small),\n"
        "            \"low_contrast\": bool(is_low_contrast), \"lap_var\": float(round(lap_var, 1)),\n"
        "            \"angle\": float(round(angle, 1)), \"original_size\": f\"{int(img.shape[1])}x{int(img.shape[0])}\",\n"
        "            \"applied\": applied}\n"
        "    return result, info\n"
    ]
})

# ---------------------------------------------------------------------------
# Cell 6 (NEW): Question Segmentation + Per-Question Extraction
# ---------------------------------------------------------------------------
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 5: Question Segmentation + Per-Question Extraction\n\n"
        "# --- Segmentation ---\n"
        "def filter_question_regions(questions, img_h, img_w):\n"
        "    filtered = []\n"
        "    for q in questions:\n"
        "        b = q[\"bbox\"]\n"
        "        top_r = b[\"y\"] / img_h\n"
        "        bot_r = (b[\"y\"] + b[\"height\"]) / img_h\n"
        "        aspect = b[\"width\"] / max(b[\"height\"], 1)\n"
        "        area_r = (b[\"width\"] * b[\"height\"]) / (img_w * img_h)\n\n"
        "        is_header = top_r < 0.08 and (b[\"height\"] < 80 or (aspect > 5 and b[\"height\"] < 120))\n"
        "        is_footer = bot_r > 0.88 and b[\"height\"] < 60\n"
        "        is_bottom = bot_r > 0.95 and b[\"height\"] < 100\n"
        "        is_small = area_r < 0.005 and (b[\"height\"] < 40 or b[\"width\"] < 80)\n"
        "        is_noise = b[\"height\"] < 30 or b[\"width\"] < 30\n\n"
        "        if not (is_header or is_footer or is_bottom or is_small or is_noise):\n"
        "            filtered.append(q)\n"
        "    return filtered\n\n"
        "def merge_fragments(regions):\n"
        "    merged = []\n"
        "    i = 0\n"
        "    while i < len(regions):\n"
        "        cur = regions[i]\n"
        "        cb = cur[\"bbox\"]\n"
        "        is_frag = cb[\"height\"] < 50 or (cb[\"height\"] < 70 and cb[\"width\"] > 5 * cb[\"height\"])\n\n"
        "        if is_frag and i + 1 < len(regions):\n"
        "            nxt = regions[i + 1]\n"
        "            nb = nxt[\"bbox\"]\n"
        "            gap = nb[\"y\"] - (cb[\"y\"] + cb[\"height\"])\n"
        "            if gap < 45:\n"
        "                ny = cb[\"y\"]\n"
        "                nh = (nb[\"y\"] + nb[\"height\"]) - ny\n"
        "                nx = min(cb[\"x\"], nb[\"x\"])\n"
        "                nw = max(cb[\"width\"], nb[\"width\"])\n"
        "                merged.append({\"idx\": 0, \"bbox\": {\"x\": nx, \"y\": ny, \"width\": nw, \"height\": nh}, \"crop\": None})\n"
        "                i += 2\n"
        "                continue\n\n"
        "        if is_frag and merged:\n"
        "            prev = merged[-1]\n"
        "            pb = prev[\"bbox\"]\n"
        "            gap = cb[\"y\"] - (pb[\"y\"] + pb[\"height\"])\n"
        "            if gap < 45:\n"
        "                merged[-1][\"bbox\"] = {\n"
        "                    \"x\": min(pb[\"x\"], cb[\"x\"]),\n"
        "                    \"y\": pb[\"y\"],\n"
        "                    \"width\": max(pb[\"width\"], cb[\"width\"]),\n"
        "                    \"height\": (cb[\"y\"] + cb[\"height\"]) - pb[\"y\"],\n"
        "                }\n"
        "                i += 1\n"
        "                continue\n\n"
"        merged.append(cur)\n"
        "        i += 1\n"
        "    return merged\n\n"
        "def deduplicate_overlaps(regions):\n"
        "    kept = []\n"
        "    for r in sorted(regions, key=lambda x: (x[\"bbox\"][\"y\"], x[\"bbox\"][\"x\"])):\n"
        "        b = r[\"bbox\"]\n"
        "        overlap = False\n"
        "        for k in kept:\n"
        "            kb = k[\"bbox\"]\n"
        "            xo = max(0, min(b[\"x\"]+b[\"width\"], kb[\"x\"]+kb[\"width\"]) - max(b[\"x\"], kb[\"x\"]))\n"
        "            yo = max(0, min(b[\"y\"]+b[\"height\"], kb[\"y\"]+kb[\"height\"]) - max(b[\"y\"], kb[\"y\"]))\n"
        "            if xo > 0 and yo > 0 and (xo*yo)/min(b[\"width\"]*b[\"height\"], kb[\"width\"]*kb[\"height\"]) > 0.5:\n"
        "                overlap = True; break\n"
        "        if not overlap:\n"
        "            kept.append(r)\n"
        "    return kept\n\n"
        "def resegment_region(img, parent, img_h, img_w):\n"
        "    region = parent[\"crop\"]\n"
        "    rh, rw = region.shape[:2]\n"
        "    gray = cv2.cvtColor(region, cv2.COLOR_RGB2GRAY)\n"
        "    _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)\n\n"
        "    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (rw // 3, max(3, rh // 120)))\n"
        "    dilated = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)\n\n"
        "    proj = np.sum(dilated, axis=1) // 255\n"
        "    thresh = rw * 0.01\n"
        "    content = proj > thresh\n\n"
        "    bands = []\n"
        "    in_b = False\n"
        "    start = 0\n"
        "    min_h = max(15, rh // 80)\n"
        "    for i in range(len(content)):\n"
        "        if content[i] and not in_b:\n"
        "            start = i; in_b = True\n"
        "        elif not content[i] and in_b:\n"
        "            if i - start > min_h:\n"
        "                bands.append((start, i))\n"
        "            in_b = False\n"
        "    if in_b and len(content) - start > min_h:\n"
        "        bands.append((start, len(content)))\n\n"
        "    px, py = parent[\"bbox\"][\"x\"], parent[\"bbox\"][\"y\"]\n"
        "    results = []\n"
        "    for ry1, ry2 in bands:\n"
"        x1 = max(0, px - 2)\n"
        "        x2 = min(img_w, px + rw + 2)\n"
        "        y1 = max(0, py + ry1 - 3)\n"
        "        y2 = min(img_h, py + ry2 + 3)\n"
        "        crop = img[y1:y2, x1:x2]\n"
        "        if crop.shape[0] >= 20 and crop.shape[1] >= 20:\n"
        "            results.append({\"idx\": 0, \"bbox\": {\"x\": int(x1), \"y\": y1, \"width\": int(x2 - x1), \"height\": int(y2 - y1)}, \"crop\": crop})\n"
        "    return results or [parent]\n\n"
        "def segment_questions(img):\n"
        "    h, w = img.shape[:2]\n"
        "    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)\n"
        "    _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)\n\n"
        "    k_h = max(5, h // 80)\n"
        "    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (w // 4, k_h))\n"
        "    dilated = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)\n\n"
        "    row_proj = np.sum(dilated, axis=1) // 255\n"
        "    threshold = w * 0.015\n"
        "    content_rows = row_proj > threshold\n\n"
        "    row_bands = []\n"
        "    in_band = False\n"
        "    start = 0\n"
        "    min_h = max(20, h // 60)\n"
        "    for i in range(len(content_rows)):\n"
        "        if content_rows[i] and not in_band:\n"
        "            start = i; in_band = True\n"
        "        elif not content_rows[i] and in_band:\n"
        "            if i - start > min_h:\n"
        "                row_bands.append((start, i))\n"
        "            in_band = False\n"
        "    if in_band and len(content_rows) - start > min_h:\n"
        "        row_bands.append((start, len(content_rows)))\n\n"
        "    questions = []\n"
        "    q_idx = 0\n\n"
        "    for ry1, ry2 in row_bands:\n"
        "        row_img = binary[ry1:ry2, :]\n"
        "        rh = row_img.shape[0]\n"
        "        vkw = max(3, w // 60)\n"
        "        vkh = max(3, int(rh * 0.25))\n"
        "        vk = cv2.getStructuringElement(cv2.MORPH_RECT, (vkw, vkh))\n"
        "        rd = cv2.morphologyEx(row_img, cv2.MORPH_CLOSE, vk)\n\n"
        "        col_proj = np.sum(rd, axis=0) // 255\n"
        "        ct = rh * 0.05\n\n"
        "        col_bands = []\n"
        "        in_b = False\n"
        "        s = 0\n"
        "        mcw = max(20, w // 40)\n"
        "        for j in range(len(col_proj)):\n"
        "            if col_proj[j] > ct and not in_b:\n"
        "                s = j; in_b = True\n"
        "            elif col_proj[j] <= ct and in_b:\n"
        "                if j - s > mcw:\n"
        "                    col_bands.append((s, j))\n"
        "                in_b = False\n"
        "        if in_b and len(col_proj) - s > mcw:\n"
        "            col_bands.append((s, len(col_proj)))\n\n"
        "        if not col_bands:\n"
        "            col_bands = [(0, w)]\n"
        "        elif len(col_bands) > 1:\n"
        "            wide = [b for b in col_bands if (b[1]-b[0]) >= w*0.2]\n"
        "            if 1 <= len(wide) <= 2:\n"
        "                col_bands = wide\n"
        "            else:\n"
        "                valid = sum(b[1]-b[0] for b in col_bands)\n"
        "                if valid < w * 0.15:\n"
        "                    col_bands = [(0, w)]\n\n"
        "        for cx1, cx2 in col_bands:\n"
        "            x1 = max(0, cx1 - 4)\n"
        "            x2 = min(w, cx2 + 4)\n"
        "            y1 = max(0, ry1 - 4)\n"
        "            y2 = min(h, ry2 + 4)\n"
        "            crop = img[y1:y2, x1:x2]\n"
        "            if crop.shape[0] < 25 or crop.shape[1] < 25:\n"
        "                continue\n"
        "            q_idx += 1\n"
        "            questions.append({\"idx\": q_idx, \"bbox\": {\"x\": int(x1), \"y\": int(y1), \"width\": int(x2-x1), \"height\": int(y2-y1)}, \"crop\": crop})\n\n"
        "    if questions:\n"
        "        questions = filter_question_regions(questions, h, w)\n"
        "        refined = []\n"
        "        for q in questions:\n"
        "            if q[\"bbox\"][\"height\"] > 350:\n"
        "                refined.extend(resegment_region(img, q, h, w))\n"
        "            else:\n"
        "                refined.append(q)\n"
"        refined = merge_fragments(refined)\n"
        "        refined = deduplicate_overlaps(refined)\n"
        "        for ni, q in enumerate(refined, 1):\n"
        "            q[\"idx\"] = ni\n"
        "        questions = refined\n"
        "    return questions\n\n"
"# --- JSON extraction ---\n"
        "def extract_json(text):\n"
        "    cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()\n"
        "    cleaned = re.sub(r'```json\\s*|```\\s*', '', cleaned).strip()\n"
        "    start = cleaned.find('{')\n"
        "    if start == -1:\n"
        "        return None, \"no JSON\"\n"
        "    depth = 0\n"
        "    end = -1\n"
        "    for i in range(start, len(cleaned)):\n"
        "        if cleaned[i] == '{':\n"
        "            depth += 1\n"
        "        elif cleaned[i] == '}':\n"
        "            depth -= 1\n"
        "        if depth == 0:\n"
        "            end = i + 1\n"
        "            break\n"
        "    if end == -1:\n"
        "        return None, \"unmatched braces\"\n"
        "    cleaned = cleaned[start:end]\n"
        "    try:\n"
        "        return json.loads(cleaned), None\n"
        "    except json.JSONDecodeError:\n"
        "        cleaned = re.sub(r',\\s*}', '}', cleaned)\n"
        "        cleaned = re.sub(r',\\s*]', ']', cleaned)\n"
        "        try:\n"
        "            return json.loads(cleaned), None\n"
        "        except json.JSONDecodeError:\n"
        "            pass\n"
        "    return None, \"parse failed\"\n\n"
"# --- Per-question analysis prompt (compact JSON schema format) ---\n"
        "PER_QUESTION_PROMPT = (\n"
        "    'You are analyzing a SINGLE QUESTION crop from a children\\'s worksheet.\\n'\n"
        "    'Read the image CAREFULLY. Your MOST IMPORTANT task: extract ALL text EXACTLY as written.\\n\\n'\n"
        "    'Return ONLY valid JSON with this exact structure (no markdown, no thinking):\\n'\n"
        "    '{\\n'\n"
        "    '  \"question_text\": \"EXACT instruction text verbatim. Read every word. If no text, set empty string.\",\\n'\n"
        "    '  \"all_visible_text\": [{\"text\": \"...\", \"position\": \"top|middle|bottom|left|right|center|label\"}],\\n'\n"
        "    '  \"instruction_verb\": \"Count|Match|Circle|Colour|Write|Trace|Tick|Draw|Join|Add|Subtract|Fill|Solve|Find|Complete\",\\n'\n"
        "    '  \"question_type\": \"Counting|Matching|Addition|Subtraction|Number-Recognition|Pattern|Comparison|Shape-Recognition|Fill-Blank|Sequencing|Tracing|Writing-Practice\",\\n'\n"
        "    '  \"question_sub_type\": \"Count-And-Write|Circle-Correct|Match-Column|Fill-Missing|Greater-Less|Before-After-Between|Ascending|Descending|True-False|Story-Sum|Complete-Pattern\",\\n'\n"
        "    '  \"structure\": \"single-item|multiple-items|matching-columns|grid|with-illustration|text-only|horizontal-row|vertical-list\",\\n'\n"
        "    '  \"item_count\": 0,\\n'\n"
        "    '  \"items\": [{\"item_number\": 1, \"text\": \"item label\", \"objects\": [], \"answer_space\": {}}],\\n'\n"
        "    '  \"objects\": [{\"name\": \"object name (singular)\", \"count\": 5, \"attributes\": [\"red\"], \"position\": \"center|scattered|row\", \"arrangement\": \"row|grid|scattered|grouped\"}],\\n'\n"
        "    '  \"total_object_count\": 0,\\n'\n"
        "    '  \"illustration_purpose\": \"counting|identification|matching|comparison|story-context|pattern-recognition|number-recognition\",\\n'\n"
        "    '  \"answer_spaces\": [{\"type\": \"blank|box|circle|line|dotted-line|tick-box|bracket\", \"count\": 1, \"location\": \"below-text|beside-text|inside-text|at-end\", \"associated_item_number\": 0}],\\n'\n"
        "    '  \"visual_elements\": [\"border|dotted-line|arrow|number-label|frame|underline|box-border\"],\\n'\n"
        "    '  \"colors_mentioned\": [\"red|blue|green|yellow|orange|purple|pink|brown|black\"],\\n'\n"
        "    '  \"relational_words\": [\"more|less|bigger|smaller|same|different|before|after|between|greater|fewer\"],\\n'\n"
        "    '  \"group_context\": {\"is_grouped\": false, \"group_id\": 0, \"group_instruction\": \"\"},\\n'\n"
        "    '  \"concept\": \"FLN concept name\",\\n'\n"
        "    '  \"learning_outcome\": \"measurable skill\",\\n'\n"
        "    '  \"cognitive_skill\": \"Remembering|Understanding|Applying|Analyzing\",\\n'\n"
        "    '  \"motor_skill\": \"Writing|Circling|Matching|Colouring|Tracing|Drawing\",\\n'\n"
        "    '  \"difficulty\": \"Easy|Medium|Hard\"\\n'\n"
        "    '}\\n\\n'\n"
        "    'RULES: question_text must be WORD FOR WORD exact copy. all_visible_text includes EVERY number, label, word fragment. '\n"
        "    'List each distinct object type once with precise count. '\n"
        "    'No answer/expected_answer/correct_answer field. '\n"
        "    'Use \"\" for empty text, [] for empty lists, 0 for zero, false for booleans.'\n"
        ")\n\n"
"def analyze_question_crop(llm, crop_img, name):\n"
        "    hc, wc = crop_img.shape[:2]\n"
        "    if min(hc, wc) > 400:\n"
        "        est = (hc // 16) * (wc // 16)\n"
        "        if est > 3000:\n"
        "            print(f\"\\n    NOTE: Large crop ({wc}x{hc}, ~{est} img tokens)\")\n"
        "    _, buffer = cv2.imencode(\".png\", cv2.cvtColor(crop_img, cv2.COLOR_RGB2BGR))\n"
        "    b64 = base64.b64encode(buffer).decode(\"utf-8\")\n"
        "    for attempt in range(1, 4):\n"
        "        hint = [\"\", \"IMPORTANT: Return valid JSON with ALL fields. No null. Do NOT include answer.\",\n"
        "                \"CRITICAL: Valid JSON only. Use \\\"\\\" for text, [] for lists. No answer.\"][attempt-1]\n"
        "        text = PER_QUESTION_PROMPT\n"
        "        if hint:\n"
        "            text += \"\\n\\n\" + hint\n"
        "        resp = llm.create_chat_completion(\n"
        "            messages=[{\"role\": \"user\", \"content\": [\n"
        "                {\"type\": \"image_url\", \"image_url\": {\"url\": f\"data:image/png;base64,{b64}\"}},\n"
        "                {\"type\": \"text\", \"text\": text + \"\\n\\nExtract everything visible in this question crop.\"},\n"
        "            ]}],\n"
        "            max_tokens=6144, temperature=0.1 + (attempt-1)*0.1,\n"
        "        )\n"
        "        raw = resp[\"choices\"][0][\"message\"][\"content\"]\n"
        "        parsed, error = extract_json(raw)\n"
        "        if parsed and isinstance(parsed, dict):\n"
        "            qt = str(parsed.get(\"question_text\", \"\") or \"\").strip()\n"
        "            qtype = str(parsed.get(\"question_type\", \"\") or \"\").strip()\n"
        "            has_items = bool(parsed.get(\"items\", []))\n"
        "            if qt or qtype or has_items:\n"
        "                return {\"file\": name, \"raw\": raw, \"parsed\": parsed, \"error\": None, \"attempts\": attempt}\n"
        "    return {\"file\": name, \"raw\": raw, \"parsed\": parsed if parsed else None,\n"
        "            \"error\": error or \"max retries\", \"attempts\": 3}\n\n"
        "print(\"Segmentation + extraction functions loaded\")\n"
    ]
})

# ---------------------------------------------------------------------------
# Cell 7 (NEW): Load images, segment, analyze per-crop, collect JSON
# ---------------------------------------------------------------------------
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 6: Load images \u2192 Segment \u2192 Analyze each crop \u2192 Collect per-question JSON\n\n"
        "print(\"=== Image Source Selection ===\")\n"
        "print(\"1) Upload images via file picker\")\n"
        "print(\"2) Load from Google Drive (mount required)\")\n"
        "src_choice = input(\"Enter 1 or 2 (default: 1): \").strip() or \"1\"\n\n"
        "def convert_pdf_to_images(pdf_path, output_dir):\n"
        "    import fitz\n"
        "    paths = []\n"
        "    pdf_name = Path(pdf_path).stem\n"
        "    pdf_dir = os.path.join(output_dir, pdf_name + \"_pdf_pages\")\n"
        "    os.makedirs(pdf_dir, exist_ok=True)\n"
        "    doc = fitz.open(pdf_path)\n"
        "    for page_num in range(len(doc)):\n"
        "        page = doc.load_page(page_num)\n"
        "        pix = page.get_pixmap()\n"
        "        img_path = os.path.join(pdf_dir, f\"{pdf_name}_page{page_num+1}.png\")\n"
        "        pix.save(img_path)\n"
        "        paths.append(img_path)\n"
        "        print(f\"    PDF page {page_num+1}/{len(doc)} -> {img_path}\")\n"
        "    doc.close()\n"
        "    return paths\n\n"
        "png_pdf_dir = os.path.join(OUTPUT_DIR, \"pdf_pages\")\n"
        "os.makedirs(png_pdf_dir, exist_ok=True)\n\n"
        "image_paths = []\n\n"
        "if src_choice == \"2\":\n"
        "    from google.colab import drive\n"
        "    drive.mount('/content/drive')\n"
        "    drive_path = input(\"Enter path in Drive (e.g., MyDrive/FLN_images): \").strip()\n"
        "    search_path = f\"/content/drive/{drive_path}\"\n"
        "    for root, _, files in os.walk(search_path):\n"
        "        for fn in sorted(files):\n"
        "            fp = os.path.join(root, fn)\n"
        "            lower = fn.lower()\n"
        "            if lower.endswith(\".zip\"):\n"
        "                zext = os.path.join(OUTPUT_DIR, \"zip_extract\")\n"
        "                os.makedirs(zext, exist_ok=True)\n"
        "                with zipfile.ZipFile(fp) as z:\n"
        "                    z.extractall(zext)\n"
        "                print(f\"  Extracted: {fn}\")\n"
        "            elif lower.endswith(('.png', '.jpg', '.jpeg', '.webp', '.bmp', '.tiff')):\n"
        "                image_paths.append(fp)\n"
        "    zext = os.path.join(OUTPUT_DIR, \"zip_extract\")\n"
        "    if os.path.exists(zext):\n"
        "        for root, _, files in os.walk(zext):\n"
        "            for fn in sorted(files):\n"
        "                if fn.lower().endswith(('.png', '.jpg', '.jpeg', '.webp', '.bmp', '.tiff')):\n"
        "                    image_paths.append(os.path.join(root, fn))\n"
        "else:\n"
        "    from google.colab import files\n"
        "    uploaded = files.upload()\n"
        "    for fn in sorted(uploaded.keys()):\n"
        "        fp = os.path.join(\"/content\", fn)\n"
        "        lower = fn.lower()\n"
        "        if lower.endswith(\".zip\"):\n"
        "            zext = os.path.join(OUTPUT_DIR, \"zip_extract\")\n"
        "            os.makedirs(zext, exist_ok=True)\n"
        "            with zipfile.ZipFile(fp) as z:\n"
        "                z.extractall(zext)\n"
        "            print(f\"  Extracted: {fn}\")\n"
        "            os.remove(fp)\n"
        "        elif lower.endswith('.pdf'):\n"
        "            new_paths = convert_pdf_to_images(fp, png_pdf_dir)\n"
        "            image_paths.extend(new_paths)\n"
        "            os.remove(fp)\n"
        "        elif lower.endswith(('.png', '.jpg', '.jpeg', '.webp', '.bmp', '.tiff')):\n"
        "            image_paths.append(fp)\n"
        "    zext = os.path.join(OUTPUT_DIR, \"zip_extract\")\n"
        "    if os.path.exists(zext):\n"
        "        for root, _, files in os.walk(zext):\n"
        "            for fn in sorted(files):\n"
        "                if fn.lower().endswith(('.png', '.jpg', '.jpeg', '.webp', '.bmp', '.tiff')):\n"
        "                    image_paths.append(os.path.join(root, fn))\n\n"
        "if not image_paths:\n"
        "    print(\"\\nNo images found. Upload images and re-run this cell.\")\n"
        "else:\n"
        "    print(f\"\\nFound {len(image_paths)} image(s)\")\n\n"
        "all_worksheets = []\n\n"
        "for idx, img_path in enumerate(image_paths, 1):\n"
        "    name = Path(img_path).name\n"
        "    stem = Path(name).stem\n"
        "    img_dir = os.path.join(OUTPUT_DIR, stem)\n"
        "    os.makedirs(img_dir, exist_ok=True)\n"
        "    crops_dir = os.path.join(img_dir, \"crops\")\n"
        "    os.makedirs(crops_dir, exist_ok=True)\n\n"
        "    print(f\"\\n{'='*60}\")\n"
        "    print(f\"[{idx}/{len(image_paths)}] {name}\")\n"
        "    print(f\"{'='*60}\")\n\n"
        "    img = cv2.imread(img_path)\n"
        "    if img is None:\n"
        "        print(f\"  FAILED: cannot read {name}\")\n"
        "        continue\n"
        "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n"
        "    print(f\"  Input: {img.shape[1]}x{img.shape[0]}\")\n\n"
        "    img, info = preprocess(img)\n"
        "    if info[\"applied\"]:\n"
        "        print(f\"  Preprocessing: {', '.join(info['applied'])}\")\n"
        "    else:\n"
        "        print(\"  Preprocessing: none needed\")\n\n"
        "    enhanced_path = os.path.join(img_dir, name)\n"
        "    cv2.imwrite(enhanced_path, cv2.cvtColor(img, cv2.COLOR_RGB2BGR))\n"
        "    display(IPyImage(img_path))\n\n"
        "    # --- SEGMENT into individual questions ---\n"
        "    questions = segment_questions(img)\n"
        "    # Re-extract crops from processed image using bounding boxes\n"
        "    for q in questions:\n"
        "        b = q[\"bbox\"]\n"
        "        q[\"crop\"] = img[b[\"y\"]:b[\"y\"]+b[\"height\"], b[\"x\"]:b[\"x\"]+b[\"width\"]]\n"
        "    print(f\"  Questions detected: {len(questions)}\")\n\n"
        "    # --- Save individual crop images ---\n"
        "    for q in questions:\n"
        "        crop_path = os.path.join(crops_dir, f\"q{q['idx']:02d}.png\")\n"
        "        cv2.imwrite(crop_path, cv2.cvtColor(q[\"crop\"], cv2.COLOR_RGB2BGR))\n\n"
        "    # --- ANALYZE each question crop with Gemma ---\n"
"    worksheet_data = {\n"
        "        \"worksheet\": name,\n"
        "        \"worksheet_info\": {\"width\": int(img.shape[1]), \"height\": int(img.shape[0]), \"preprocessing\": info},\n"
        "        \"questions\": []\n"
        "    }\n\n"
        "    _t_start = time.time()\n"
        "    for q in questions:\n"
        "        q_idx = q[\"idx\"]\n"
        "        crop_name = f\"q{q_idx:02d}.png\"\n"
        "        print(f\"  [{q_idx}/{len(questions)}] Analyzing...\", end=\" \", flush=True)\n\n"
        "        result = analyze_question_crop(llm, q[\"crop\"], crop_name)\n"
        "        spec = result.get(\"parsed\") or {}\n"
        "        confidence = max(0.0, min(1.0, 1.0 - (result[\"attempts\"] - 1) * 0.1)) if result[\"parsed\"] else 0.0\n\n"
        "        entry = {\n"
        "            \"question_number\": q_idx,\n"
        "            \"bounding_box\": q[\"bbox\"],\n"
        "            \"analysis_attempts\": result[\"attempts\"],\n"
        "            \"analysis_error\": result[\"error\"],\n"
"            \"confidence\": round(confidence, 2),\n"
        "            \"raw_response\": result.get(\"raw\", \"\") or \"\",\n"
        "            \"question_text\": spec.get(\"question_text\", \"\") or \"\",\n"
        "            \"all_visible_text\": spec.get(\"all_visible_text\", []) or [],\n"
        "            \"instruction_verb\": spec.get(\"instruction_verb\", \"\") or \"\",\n"
        "            \"question_type\": spec.get(\"question_type\", \"\") or \"\",\n"
        "            \"question_sub_type\": spec.get(\"question_sub_type\", \"\") or \"\",\n"
        "            \"structure\": spec.get(\"structure\", \"\") or \"\",\n"
        "            \"item_count\": spec.get(\"item_count\", 0) or 0,\n"
        "            \"items\": spec.get(\"items\", []) or [],\n"
        "            \"objects\": spec.get(\"objects\", []) or [],\n"
        "            \"total_object_count\": spec.get(\"total_object_count\", 0) or 0,\n"
        "            \"illustration_purpose\": spec.get(\"illustration_purpose\", \"\") or \"\",\n"
        "            \"answer_spaces\": spec.get(\"answer_spaces\", []) or [],\n"
        "            \"visual_elements\": spec.get(\"visual_elements\", []) or [],\n"
        "            \"colors_mentioned\": spec.get(\"colors_mentioned\", []) or [],\n"
        "            \"relational_words\": spec.get(\"relational_words\", []) or [],\n"
        "            \"group_context\": spec.get(\"group_context\", {}) or {},\n"
        "            \"concept\": spec.get(\"concept\", \"\") or \"\",\n"
        "            \"learning_outcome\": spec.get(\"learning_outcome\", \"\") or \"\",\n"
        "            \"cognitive_skill\": spec.get(\"cognitive_skill\", \"\") or \"\",\n"
        "            \"motor_skill\": spec.get(\"motor_skill\", \"\") or \"\",\n"
        "            \"difficulty\": spec.get(\"difficulty\", \"\") or \"\",\n"
        "        }\n"
        "        worksheet_data[\"questions\"].append(entry)\n\n"
        "        qt_preview = entry[\"question_text\"][:60] if entry[\"question_text\"] else \"[empty]\"\n"
        "        qt_type = entry[\"question_type\"] or \"[unknown]\"\n"
        "        print(f\"Q{q_idx}: {qt_type} | {qt_preview}\")\n\n"
        "    elapsed = time.time() - _t_start\n"
        "    print(f\"  Elapsed: {elapsed:.0f}s ({elapsed/60:.1f}min)\")\n\n"
        "    # --- Save per-worksheet JSON ---\n"
        "    out_path = os.path.join(img_dir, f\"{stem}_questions.json\")\n"
        "    with open(out_path, \"w\") as f:\n"
        "        json.dump(worksheet_data, f, indent=2, ensure_ascii=False)\n"
        "    print(f\"  Saved: {out_path}\")\n"
        "    all_worksheets.append(worksheet_data)\n\n"
        "# --- Summary ---\n"
        "if image_paths:\n"
        "    total_qs = sum(len(w[\"questions\"]) for w in all_worksheets)\n"
        "    print(f\"\\n{'='*60}\")\n"
        "    print(f\"COMPLETE: {len(all_worksheets)} worksheet(s), {total_qs} questions extracted\")\n"
        "    print(f\"{'='*60}\")\n"
        "    manifest_path = os.path.join(OUTPUT_DIR, \"batch_manifest.json\")\n"
"    with open(manifest_path, \"w\") as f:\n"
        "        json.dump({\"worksheets\": all_worksheets}, f, indent=2, ensure_ascii=False)\n"
        "    print(f\"Manifest: {manifest_path}\")\n"
        "    # --- Batch CSV summary ---\n"
        "    csv_summary = os.path.join(OUTPUT_DIR, \"all_questions_summary.csv\")\n"
        "    with open(csv_summary, \"w\", newline=\"\") as f:\n"
        "        w = csv.writer(f)\n"
        "        w.writerow([\"worksheet\",\"qnum\",\"type\",\"subtype\",\"verb\",\"text\",\"objects\",\"concept\",\"difficulty\",\"confidence\"])\n"
        "        for ws in all_worksheets:\n"
        "            fn = ws[\"worksheet\"]\n"
        "            for qe in ws[\"questions\"]:\n"
        "                w.writerow([fn, qe[\"question_number\"], qe[\"question_type\"], qe[\"question_sub_type\"],\n"
        "                            qe[\"instruction_verb\"], qe[\"question_text\"][:200], qe[\"total_object_count\"],\n"
        "                            qe[\"concept\"], qe[\"difficulty\"], qe[\"confidence\"]])\n"
        "    print(f\"CSV summary: {csv_summary}\")\n"
    ]
})

# ---------------------------------------------------------------------------
# Cell 8: Package and download results
# ---------------------------------------------------------------------------
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Cell 7: Package and download results\n\n"
        "!zip -r /content/FLN_Results.zip /content/FLN_Results\n\n"
        "from google.colab import files\n"
        "files.download(\"/content/FLN_Results.zip\")\n\n"
        "print(\"\\nDone! Results downloaded.\")\n"
    ]
})

# Build notebook JSON
notebook = {
    "metadata": {
        "kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
        "language_info": {
            "name": "python", "version": "3.12.13", "mimetype": "text/x-python",
            "codemirror_mode": {"name": "ipython", "version": 3},
            "pygments_lexer": "ipython3", "nbconvert_exporter": "python", "file_extension": ".py",
        },
        "accelerator": "GPU",
        "colab": {"provenance": [], "gpuType": "T4"},
    },
    "nbformat_minor": 4,
    "nbformat": 4,
    "cells": cells,
}

output_path = r"C:\Users\USER\Desktop\private_IITRPR\IITRPR_INTERN\question_paper_question_extract\gemma26b_image_metrics_illustrator_colab.ipynb"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Wrote: {output_path}")
print(f"Cells: {len(cells)}")
